name: Build
on: [push]
jobs: 
  deploy-to-impaas:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ImPaaS-Deploy
      uses: /impaas/impaas-deploy@v3
      with:
        app-name: mm1121-sse-app-l2
        deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
        method: PLATFORM